<?php  
/*
$hae_julkaisunkanvan_tiedot="SELECT Jufo_ID, Level, Name, Abbreviation, Other_Title, Title_Details, ISSNL, ISSN1, ISSN2, ISBN, Continues, Continued_by, Type, Field, Subfield, Website, Country, Publisher, Language, Year_Start, Year_End, Active, Norway_Level, Denmark_Level, SJR_SJR, SNIP, IPP, DOAJ_Index, Sherpa_Romeo_Code, CreatedAt, ModifiedAt, Active_Binary, Predator, Jufo_2012, Jufo_2013, Jufo_2014, Jufo_2015, Fields, Scientific, Professional, Substitutive_Channel, Grounds_Removal FROM Publications LIMIT 10";
*/

# Haetaan  tiedot esivalmistelu 
$kanava_hae_jkanava_pre1="select Fields from Publications where jufo_id = %PARAM1%";



$hae_julkaisunkanvan_tiedot="SELECT IFNULL(Jufo_ID, '') as Jufo_ID, IFNULL(Channel_ID, '') as Channel_ID, IFNULL(Source, '') as Source, IFNULL(Level, '') as Level ,IFNULL(Name, '') as Name, IFNULL(Abbreviation, '') as Abbreviation, 
 IFNULL(Other_Title, '') as Other_Title, IFNULL(Title_Details, '') as Title_Details, IFNULL(ISSNL, '') as ISSNL, IFNULL(ISSN1, '') as ISSN1, IFNULL(ISSN2, '') as ISSN2, IFNULL(ISBN, '') as ISBN, IFNULL(Continues, '') as Continues, IFNULL(Continued_by, '') as Continued_by, IFNULL(Type, '') as Type, IFNULL(Field, '') as Field, IFNULL(Subfield, '') as Subfield, IFNULL(Website, '') as Website ,IFNULL(Country, '') as Country, IFNULL(Publisher, '') as Publisher, IFNULL(Language, '') as Language, IFNULL(Year_Start, '') as Year_Start, 
 IFNULL(Year_End, '') as Year_End, IFNULL(Active, '') as Active, IFNULL(Norway_Level, '') as Norway_Level, IFNULL(Denmark_Level, '') as Denmark_Level, IFNULL(SJR_SJR, '') as SJR_SJR, IFNULL(SNIP, '') as  SNIP, IFNULL(IPP, '') as IPP, IFNULL(DOAJ_Index, '') as DOAJ_Index, IFNULL(Sherpa_Romeo_Code, '') as Sherpa_Romeo_Code, IFNULL(CreatedAt, '') as CreatedAt, IFNULL(ModifiedAt, '') as ModifiedAt, IFNULL(Active_Binary, '') as Active_Binary ,IFNULL(Jufo_2012, '') as Jufo_2012, IFNULL(Jufo_2013, '') as Jufo_2013, 
IFNULL(Jufo_2014, '') as Jufo_2014, IFNULL(Jufo_2015, '') as Jufo_2015, IFNULL(Jufo_2016, '') as Jufo_2016, IFNULL(Jufo_2017, '') as Jufo_2017, IFNULL(Jufo_2018, '') as Jufo_2018, IFNULL(Jufo_2019, '') as Jufo_2019, IFNULL(Fields, '') as Fields, IFNULL(Scientific, '') as Scientific, IFNULL(Professional, '') as Professional, IFNULL(Substitutive_Channel, '') as Substitutive_Channel, IFNULL(Grounds_Removal, '') as Grounds_Removal FROM Publications UNION ALL SELECT IFNULL(Jufo_ID, '') as Jufo_ID, IFNULL(Channel_ID, '') as Channel_ID, IFNULL(Source, '') as Source, IFNULL(Level, '') as Level ,IFNULL(Name, '') as Name, IFNULL(Abbreviation, '') as Abbreviation, IFNULL(Other_Title, '') as Other_Title, IFNULL(Title_Details, '') as Title_Details, IFNULL(ISSNL, '') as ISSNL, IFNULL(ISSN1, '') as ISSN1, IFNULL(ISSN2, '') as ISSN2, IFNULL(ISBN, '') as ISBN, IFNULL(Continues, '') as Continues, IFNULL(Continued_by, '') as Continued_by, IFNULL(Type, '') as Type, IFNULL(Field, '') as Field, IFNULL(Subfield, '') as Subfield, IFNULL(Website, '') as Website ,IFNULL(Country, '') as Country, IFNULL(Publisher, '') as Publisher, IFNULL(Language, '') as Language, IFNULL(Year_Start, '') as Year_Start, IFNULL(Year_End, '') as Year_End, IFNULL(Active, '') as Active, IFNULL(Norway_Level, '') as Norway_Level, IFNULL(Denmark_Level, '') as Denmark_Level, IFNULL(SJR_SJR, '') as SJR_SJR, IFNULL(SNIP, '') as  SNIP, IFNULL(IPP, '') as IPP, IFNULL(DOAJ_Index, '') as DOAJ_Index, IFNULL(Jfi_Index, '') as Jfi_Index, IFNULL(Bfeld_Index, '') as Bfeld_Index, IFNULL(Virta_Gold, '') as Virta_Gold, IFNULL(Virta_Hybrid, '') as Virta_Hybrid, IFNULL(Virta_Green, '') as Virta_Green, IFNULL(Sherpa_Romeo_Code, '') as Sherpa_Romeo_Code, IFNULL(CreatedAt, '') as CreatedAt, IFNULL(ModifiedAt, '') as ModifiedAt, 
IFNULL(Active_Binary, '') as Active_Binary ,IFNULL(Jufo_2012, '') as Jufo_2012, IFNULL(Jufo_2013, '') as Jufo_2013, IFNULL(Jufo_2014, '') as Jufo_2014, IFNULL(Jufo_2015, '') as Jufo_2015, IFNULL(Jufo_2016, '') as Jufo_2016, IFNULL(Jufo_2017, '') as Jufo_2017, IFNULL(Jufo_2018, '') as Jufo_2018, IFNULL(Jufo_2019, '') as Jufo_2019, IFNULL(Fields, '') as Fields, IFNULL(Scientific, '') as Scientific, IFNULL(Professional, '') as Professional, IFNULL(Substitutive_Channel, '') as Substitutive_Channel, 
IFNULL(Grounds_Removal, '') as Grounds_Removal FROM ProfessionalsAndGenerals LIMIT 10;";



$kanava_hae_jkanava="SELECT IFNULL(p.Jufo_ID, '') as Jufo_ID, IFNULL(p.Level, '') as Level ,IFNULL(p.Name, '') as Name, IFNULL(p.Abbreviation, '') as Abbreviation, IFNULL(p.Other_Title, '') as Other_Title, IFNULL(p.Title_Details, '') as Title_Details, IFNULL(p.ISSNL, '') as ISSNL, IFNULL(p.ISSN1, '') as ISSN1, IFNULL(p.ISSN2, '') as ISSN2, IFNULL(p.ISBN, '') as ISBN, IFNULL(p.Continues, '') as Continues, IFNULL(p.Continued_by, '') as Continued_by, IFNULL(p.Type, '') as Type, IFNULL(p.Field, '') as Field, IFNULL(p.Subfield, '') as Subfield, IFNULL(p.Website, '') as Website ,IFNULL(p.Country, '') as Country, IFNULL(p.Publisher, '') as Publisher, IFNULL(p.Language, '') as Language, IFNULL(p.Year_Start, '') as Year_Start, IFNULL(p.Year_End, '') as Year_End, IFNULL(p.Active, '') as Active, IFNULL(p.Norway_Level, '') as Norway_Level, IFNULL(p.Denmark_Level, '') as Denmark_Level, IFNULL(p.SJR_SJR, '') as SJR_SJR, IFNULL(p.SNIP, '') as  SNIP, IFNULL(p.IPP, '') as IPP, IFNULL(p.DOAJ_Index, '') as DOAJ_Index, IFNULL(p.Jfi_Index, '') as Jfi_Index, IFNULL(p.Bfeld_Index, '') as Bfeld_Index, IFNULL(p.Virta_Gold, '') as Virta_Gold, IFNULL(p.Virta_Hybrid, '') as Virta_Hybrid, IFNULL(p.Virta_Green, '') as Virta_Green, IFNULL(p.Sherpa_Romeo_Code, '') as Sherpa_Romeo_Code, IFNULL(p.CreatedAt, '') as CreatedAt, IFNULL(p.ModifiedAt, '') as ModifiedAt, IFNULL(p.Active_Binary, '') as Active_Binary ,IFNULL(p.Jufo_2012, '') as Jufo_2012, IFNULL(p.Jufo_2013, '') as Jufo_2013, IFNULL(p.Jufo_2014, '') as Jufo_2014, IFNULL(p.Jufo_2015, '') as Jufo_2015, IFNULL(p.Jufo_2016, '') as Jufo_2016, IFNULL(p.Jufo_2017, '') as Jufo_2017, IFNULL(p.Jufo_2018, '') as Jufo_2018, IFNULL(p.Jufo_2019, '') as Jufo_2019, group_concat(e.Name SEPARATOR '; ') as Fields, IFNULL(p.Scientific, '') as Scientific, IFNULL(p.Professional, '') as Professional, IFNULL(p.Jufo_History, '') as Jufo_history, IFNULL(p.Substitutive_Channel, '') as Substitutive_Channel, IFNULL(p.Grounds_Removal, '') as Grounds_Removal FROM Publications p CROSS JOIN ExtEvaluationCategories e on e.Source_ID = 6 and e.id in (%PARAM2%)
WHERE p.jufo_ID = %PARAM1%;";


# Julkaisukanavan tiedot ilma tieteenaljo
$kanava_hae_jkanava_b="SELECT IFNULL(p.Jufo_ID, '') as Jufo_ID, IFNULL(p.Channel_ID, '') as Channel_ID, IFNULL(p.Source, '') as Source, IFNULL(p.Level, '') as Level ,IFNULL(p.Name, '') as Name, IFNULL(p.Abbreviation, '') as Abbreviation, 
IFNULL(p.Other_Title, '') as Other_Title, IFNULL(p.Title_Details, '') as Title_Details, IFNULL(p.ISSNL, '') as ISSNL, IFNULL(p.ISSN1, '') as ISSN1, IFNULL(p.ISSN2, '') as ISSN2, IFNULL(p.ISBN, '') as ISBN, IFNULL(p.Continues, '') as Continues, IFNULL(p.Continued_by, '') as Continued_by, IFNULL(p.Type, '') as Type, IFNULL(p.Field, '') as Field, IFNULL(p.Subfield, '') as Subfield, IFNULL(p.Website, '') as Website, IFNULL(p.Country, '') as Country, IFNULL(p.Publisher, '') as Publisher, IFNULL(p.Language, '') as Language, IFNULL(p.Year_Start, '') as Year_Start, IFNULL(p.Year_End, '') as Year_End, IFNULL(p.Active, '') as Active, IFNULL(p.Norway_Level, '') as Norway_Level, 
IFNULL(p.Denmark_Level, '') as Denmark_Level, IFNULL(p.SJR_SJR, '') as SJR_SJR, IFNULL(p.SNIP, '') as  SNIP, IFNULL(p.IPP, '') as IPP, IFNULL(p.DOAJ_Index, '') as DOAJ_Index, IFNULL(p.Jfi_Index, '') as Jfi_Index, IFNULL(p.Bfeld_Index, '') as Bfeld_Index, IFNULL(p.Virta_Gold, '') as Virta_Gold, IFNULL(p.Virta_Hybrid, '') as Virta_Hybrid, IFNULL(p.Virta_Green, '') as Virta_Green, IFNULL(p.Sherpa_Romeo_Code, '') as Sherpa_Romeo_Code, IFNULL(p.CreatedAt, '') as CreatedAt, IFNULL(p.ModifiedAt, '') as ModifiedAt, IFNULL(p.Active_Binary, '') as Active_Binary ,IFNULL(p.Jufo_2012, '') as Jufo_2012, IFNULL(p.Jufo_2013, '') as Jufo_2013, IFNULL(p.Jufo_2014, '') as Jufo_2014, IFNULL(p.Jufo_2015, '') as Jufo_2015, IFNULL(p.Jufo_2016, '') as Jufo_2016, IFNULL(p.Jufo_2017, '') as Jufo_2017, IFNULL(p.Jufo_2018, '') as Jufo_2018, IFNULL(p.Jufo_2019, '') as Jufo_2019, '' as Fields, 
IFNULL(p.Scientific, '') as Scientific, IFNULL(p.Professional, '') as Professional, IFNULL(p.Jufo_History, '') as Jufo_history, IFNULL(p.Substitutive_Channel, '') as Substitutive_Channel, IFNULL(p.Grounds_Removal, '') as Grounds_Removal FROM Publications p WHERE p.jufo_ID = %PARAM1% UNION ALL SELECT IFNULL(pg.Jufo_ID, '') as Jufo_ID, IFNULL(pg.Channel_ID, '') as Channel_ID, IFNULL(pg.Source, '') as Source, IFNULL(pg.Level, '') as Level ,IFNULL(pg.Name, '') as Name, IFNULL(pg.Abbreviation, '') as Abbreviation, IFNULL(pg.Other_Title, '') as Other_Title, IFNULL(pg.Title_Details, '') as Title_Details, IFNULL(pg.ISSNL, '') as ISSNL, IFNULL(pg.ISSN1, '') as ISSN1, IFNULL(pg.ISSN2, '') as ISSN2, IFNULL(pg.ISBN, '') as ISBN, IFNULL(pg.Continues, '') as Continues, IFNULL(pg.Continued_by, '') as Continued_by, IFNULL(pg.Type, '') as Type, IFNULL(pg.Field, '') as Field, IFNULL(pg.Subfield, '') as Subfield, IFNULL(pg.Website, '') as Website,
IFNULL(pg.Country, '') as Country, IFNULL(pg.Publisher, '') as Publisher, IFNULL(pg.Language, '') as Language, IFNULL(pg.Year_Start, '') as Year_Start, IFNULL(pg.Year_End, '') as Year_End, IFNULL(pg.Active, '') as Active, IFNULL(pg.Norway_Level, '') as Norway_Level, IFNULL(pg.Denmark_Level, '') as Denmark_Level, IFNULL(pg.SJR_SJR, '') as SJR_SJR, IFNULL(pg.SNIP, '') as  SNIP, IFNULL(pg.IPP, '') as IPP, IFNULL(pg.DOAJ_Index, '') as DOAJ_Index, IFNULL(pg.Jfi_Index, '') as Jfi_Index, IFNULL(pg.Bfeld_Index, '') as Bfeld_Index, IFNULL(pg.Virta_Gold, '') as Virta_Gold, IFNULL(pg.Virta_Hybrid, '') as Virta_Hybrid, IFNULL(pg.Virta_Green, '') as Virta_Green, IFNULL(pg.Sherpa_Romeo_Code, '') as Sherpa_Romeo_Code, IFNULL(pg.CreatedAt, '') as CreatedAt, IFNULL(pg.ModifiedAt, '') as ModifiedAt, IFNULL(pg.Active_Binary, '') as Active_Binary ,IFNULL(pg.Jufo_2012, '') as Jufo_2012, IFNULL(pg.Jufo_2013, '') as Jufo_2013, IFNULL(pg.Jufo_2014, '') as Jufo_2014, IFNULL(pg.Jufo_2015, '') as Jufo_2015, IFNULL(pg.Jufo_2016, '') as Jufo_2016, IFNULL(pg.Jufo_2017, '') as Jufo_2017, IFNULL(pg.Jufo_2018, '') as Jufo_2018, IFNULL(pg.Jufo_2019, '') as Jufo_2019, '' as Fields, IFNULL(pg.Scientific, '') as Scientific, IFNULL(pg.Professional, '') as Professional, IFNULL(pg.Jufo_History, '') as Jufo_history, IFNULL(pg.Substitutive_Channel, '') as Substitutive_Channel, IFNULL(pg.Grounds_Removal, '') as Grounds_Removal FROM ProfessionalsAndGenerals pg WHERE pg.Channel_ID = %PARAM1%;";

$kanava_etsi_jkanava="select IFNULL(jufo_id, '') as Jufo_ID, concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type from Publications where Type = '%PARAM3%' and name like '%%PARAM2%%' UNION ALL select IFNULL(jufo_id, '') as Jufo_ID, concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type from ProfessionalsAndGenerals where Type = '%PARAM3%' and name like '%%PARAM2%%';";


$kanava_etsi_jkanava_issn="select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type 
from Publications where Type = '%PARAM3%' and issn1 like '%%PARAM2%%' or issn2 like '%%PARAM2%%' UNION ALL select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type from ProfessionalsAndGenerals where Type = '%PARAM3%' and issn1 like '%%PARAM2%%' or issn2 like '%%PARAM2%%';";


$kanava_etsi_jkanava_isbn="select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type 
from Publications where Type = '%PARAM3%' and isbn like '%%PARAM2%%' UNION ALL select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type from ProfessionalsAndGenerals where Type = '%PARAM3%' and isbn like '%%PARAM2%%';";


$kanava_etsi_jkanava_lyhenne="select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type 
from Publications where Type = '%PARAM3%' and Abbreviation like '%PARAM2%%' UNION ALL select IFNULL(jufo_id, '') as Jufo_ID,  concat('%PARAM1%', IFNULL(jufo_id, '')) as Link, IFNULL(name, '') as Name, IFNULL(Type, '') as Type from ProfessionalsAndGenerals where Type = '%PARAM3%' and Abbreviation like '%PARAM2%%';";



?>
